# Generated by Django 5.2.17 on 2026-09-14 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderRefresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('asset_type', models.CharField(choices=[('FIXED_INCOME', 'Fixed income'), ('USD', 'USD'), ('CRYPTO', 'Crypto'), ('IRAN_STOCK', 'Iran stock'), ('US_STOCK', 'US stock'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('MANUAL', 'Manual')], max_length=30)),
                ('unit', models.CharField(choices=[('UNIT', 'Unit'), ('GRAM', 'Gram')], default='UNIT', max_length=20)),
                ('pricing_mode', models.CharField(choices=[('MARKET', 'Market'), ('MANUAL', 'Manual')], default='MARKET', max_length=20)),
                ('price_provider', models.CharField(blank=True, max_length=50)),
                ('provider_symbol', models.CharField(blank=True, max_length=100)),
                ('manual_price_currency', models.CharField(blank=True, default='IRT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='portfolio.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=10, max_digits=28)),
                ('currency', models.CharField(max_length=10)),
                ('provider', models.CharField(max_length=50)),
                ('provider_symbol', models.CharField(blank=True, max_length=100)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='portfolio.asset')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['asset', 'captured_at'], name='portfolio_a_asset_i_95c73a_idx'), models.Index(fields=['provider', 'captured_at'], name='portfolio_a_provide_a9c7f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=28)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True)),
                ('transaction_currency', models.CharField(blank=True, default='IRT', max_length=10)),
                ('executed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolio.asset')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.location')),
            ],
            options={
                'ordering': ['executed_at', 'id'],
                'indexes': [models.Index(fields=['asset', 'executed_at'], name='portfolio_t_asset_i_2ceb6f_idx'), models.Index(fields=['executed_at'], name='portfolio_t_execute_bb3acb_idx')],
            },
        ),
    ]
